# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DHOI_9hTPw7ng7Dgt5PbwWj8-xdDD9i
"""

! pip install duckdb

import duckdb

# 1. Create the in-memory DuckDB connection
con = duckdb.connect(database=':memory:')

# 2. Create tables and insert rows
setup_sql = """
-- USERS
CREATE TABLE users (id INT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100) UNIQUE, phone VARCHAR(20), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO users VALUES
(1, 'Ana', 'Gomez', 'cliente@example.com', '555-0101', '2026-02-15 10:00:00'),
(2, 'Carlos', 'Ruiz', 'carlos.r@mail.com', NULL, '2026-03-01 14:30:00'),
(3, 'Beatriz', 'Perez', 'bea.p@mail.com', '555-0103', '2026-03-10 09:15:00'),
(4, 'David', 'Lopes', 'david.l@mail.com', NULL, '2026-01-20 11:20:00'),
(5, 'Elena', 'Torres', 'elena.t@mail.com', '555-0105', '2026-03-16 16:45:00'),
(6, 'Fernando', 'Silva', 'fer.s@mail.com', '555-0106', '2026-02-28 08:00:00'),
(7, 'Gabriela', 'Cruz', 'gabi.c@mail.com', '555-0107', '2026-03-05 13:10:00'),
(8, 'Hugo', 'Diaz', 'hugo.d@mail.com', NULL, '2026-03-12 17:55:00'),
(9, 'Isabel', 'Ortiz', 'isa.o@mail.com', '555-0109', '2026-01-05 12:00:00'),
(10, 'Jorge', 'Rios', 'jorge.r@mail.com', '555-0110', '2026-03-17 09:00:00');

-- CATEGORIES
CREATE TABLE categories (id INT PRIMARY KEY, parent_id INT, name VARCHAR(100), description TEXT);
INSERT INTO categories VALUES
(1, NULL, 'Electronics', 'Gadgets and devices'),
(2, NULL, 'Clothing', 'Apparel and accessories'),
(3, 1, 'Laptops', 'Computers and notebooks'),
(4, 1, 'Smartphones', 'Mobile devices'),
(5, 2, 'Menswear', 'Men clothing'),
(6, 5, 'Shirts', 'T-shirts and button-downs'),
(7, 5, 'Pants', 'Jeans and trousers'),
(8, 2, 'Womenswear', 'Women clothing'),
(9, 8, 'Dresses', 'Casual and formal dresses'),
(10, NULL, 'Home & Garden', 'Furniture and tools');

-- PRODUCTS
CREATE TABLE products (id INT PRIMARY KEY, category_id INT, name VARCHAR(255), price DECIMAL(10, 2), stock_quantity INT, sku VARCHAR(50) UNIQUE, is_active BOOLEAN);
INSERT INTO products VALUES
(1, 3, 'Pro Laptop 15', 1299.99, 15, 'PROD-123', TRUE),
(2, 4, 'Smartphone X', 799.50, 0, 'SKU-002', TRUE),
(3, 6, 'Cotton T-Shirt', 19.99, 100, 'SKU-003', TRUE),
(4, 7, 'Denim Jeans', 49.99, 50, 'SKU-004', TRUE),
(5, 9, 'Summer Dress', 39.99, 0, 'SKU-005', FALSE),
(6, 3, 'Basic Laptop 13', 599.00, 30, 'SKU-006', TRUE),
(7, 10, 'Garden Shovel', 25.00, 20, 'SKU-007', TRUE),
(8, 10, 'Table Lamp', 35.50, 10, 'SKU-008', FALSE),
(9, 4, 'Budget Phone', 299.00, 0, 'SKU-009', TRUE),
(10, 6, 'Polo Shirt', 29.99, 45, 'SKU-010', TRUE);

-- ORDERS
CREATE TABLE orders (id INT PRIMARY KEY, user_id INT, order_date TIMESTAMP, status VARCHAR(50), total_amount DECIMAL(10, 2));
INSERT INTO orders VALUES
(1, 1, '2024-05-10 10:00:00', 'cancelled', 1299.99),
(2, 1, '2026-03-17 08:30:00', 'pending', 49.99),
(3, 2, '2026-03-16 14:00:00', 'completed', 799.50),
(4, 3, '2024-11-20 09:15:00', 'cancelled', 39.99),
(5, 4, '2026-03-17 11:20:00', 'completed', 599.00),
(6, 5, '2026-02-28 16:45:00', 'completed', 19.99),
(7, 6, '2026-03-15 08:00:00', 'pending', 25.00),
(8, 7, '2026-03-17 13:10:00', 'pending', 35.50),
(9, 8, '2024-01-12 17:55:00', 'completed', 299.00),
(10, 9, '2026-03-17 12:00:00', 'pending', 29.99);

-- ORDER_ITEMS
CREATE TABLE order_items (id INT PRIMARY KEY, order_id INT, product_id INT, quantity INT, unit_price DECIMAL(10, 2));
INSERT INTO order_items VALUES
(1, 1, 1, 1, 1299.99),
(2, 2, 4, 1, 49.99),
(3, 3, 2, 1, 799.50),
(4, 4, 5, 1, 39.99),
(5, 5, 6, 1, 599.00),
(6, 6, 3, 1, 19.99),
(7, 7, 7, 1, 25.00),
(8, 8, 8, 1, 35.50),
(9, 9, 9, 1, 299.00),
(10, 10, 10, 1, 29.99);

-- REVIEWS
CREATE TABLE reviews (id INT PRIMARY KEY, product_id INT, user_id INT, rating INT, comment TEXT, created_at TIMESTAMP);
INSERT INTO reviews VALUES
(1, 1, 2, 5, 'Amazing laptop!', '2026-03-15 10:00:00'),
(2, 2, 3, 1, 'Battery drains too fast.', '2026-02-20 14:30:00'),
(3, 3, 4, 4, 'Good quality cotton.', '2026-03-10 09:15:00'),
(4, 1, 5, 5, 'Best purchase ever.', '2026-03-16 11:20:00'),
(5, 5, 6, 2, 'Size runs small.', '2026-01-20 16:45:00'),
(6, 6, 7, 4, 'Great value for money.', '2026-02-28 08:00:00'),
(7, 7, 8, 5, 'Sturdy and reliable.', '2026-03-05 13:10:00'),
(8, 8, 9, 1, 'Arrived broken.', '2026-03-12 17:55:00'),
(9, 9, 10, 3, 'Its okay for the price.', '2026-01-05 12:00:00'),
(10, 10, 1, 5, 'Fits perfectly.', '2026-03-17 09:00:00');

-- SHIPPING_DETAILS
CREATE TABLE shipping_details (id INT PRIMARY KEY, order_id INT, address_line1 VARCHAR(255), city VARCHAR(100), state VARCHAR(100), postal_code VARCHAR(20), tracking_number VARCHAR(100), carrier VARCHAR(50));
INSERT INTO shipping_details VALUES
(1, 1, '123 Main St', 'Bogota', 'Cundinamarca', '110111', 'TRK-001', 'FedEx'),
(2, 2, '456 Elm St', 'Medellin', 'Antioquia', '050001', 'TRK-002', 'UPS'),
(3, 3, '789 Oak Ave', 'Cali', 'Valle', '760001', 'TRK-003', 'FedEx'),
(4, 4, '321 Pine Rd', 'Cartagena', 'Bolivar', '130001', 'TRK-004', 'DHL'),
(5, 5, '654 Cedar Ln', 'Barranquilla', 'Atlantico', '080001', 'TRK-005', 'FedEx'),
(6, 6, '987 Birch Blvd', 'Bucaramanga', 'Santander', '680001', 'TRK-006', 'UPS'),
(7, 7, '147 Walnut St', 'Pereira', 'Risaralda', '660001', 'TRK-007', 'FedEx'),
(8, 8, '258 Cherry Ct', 'Manizales', 'Caldas', '170001', 'TRK-008', 'DHL'),
(9, 9, '369 Spruce Way', 'Santa Marta', 'Magdalena', '470001', 'TRK-009', 'FedEx'),
(10, 10, '741 Ash Dr', 'Cucuta', 'Norte de Santander', '540001', 'TRK-010', 'UPS');

-- PROMOTIONS
CREATE TABLE promotions (id INT PRIMARY KEY, code VARCHAR(50) UNIQUE, discount_percentage DECIMAL(5, 2), start_date DATE, end_date DATE, is_active BOOLEAN);
INSERT INTO promotions VALUES
(1, 'VERANO20', 20.00, '2026-03-01', '2026-03-31', TRUE),
(2, 'WELCOME10', 10.00, '2026-01-01', '2026-12-31', TRUE),
(3, 'FLASH50', 50.00, '2026-03-15', '2026-03-20', TRUE),
(4, 'WINTER30', 30.00, '2025-12-01', '2026-02-28', FALSE),
(5, 'VIP25', 25.00, '2026-01-01', '2026-12-31', TRUE),
(6, 'SPRING15', 15.00, '2026-03-20', '2026-06-20', FALSE),
(7, 'BF2025', 40.00, '2025-11-25', '2025-11-30', FALSE),
(8, 'CYBER2025', 45.00, '2025-12-01', '2025-12-02', FALSE),
(9, 'FREESHIP', 100.00, '2026-03-01', '2026-03-31', TRUE),
(10, 'HALLOWEEN', 15.00, '2025-10-25', '2025-10-31', FALSE);
"""

# Run the setup SQL
con.execute(setup_sql)
print("Database successfully created and populated with 10 rows per table in DuckDB!")

# Query test
display(con.execute("SELECT * FROM users LIMIT 5;").df())